---
# Lambda School Data Science - Intro to Python  
---
# Assignment 02 - Python Lists & Loops

*(updated to correct an assertion error in Solution 1.3 - 10 Aug 2020)*

##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_assign2"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!

---

## Part 1: Lists

### Use the provided lists to answer the questions and prompts.
Make sure to run the cell below so the lists are declared with their corresponding values.

These lists are one-dimensional where each element contains one value. The data types of these lists is checked by using the `type()` function.

In [39]:
# DO NOT EDIT THIS CELL

# EXAMPLE data (you don't need to do anything other than run this cell)
# Lists of personal data
heights = [184, 177, 190, 188, 159, 166]
weights = [84.5, 81.8, 86.1, 92.2, 69.6, 72.0 ]
names = ['John', 'Ryan', 'Bobby', 'Pete', 'Esther', 'Jane']

# Checking the data type 
print(type(heights), type(weights), type(names))

<class 'list'> <class 'list'> <class 'list'>

All three variables are a `list`. We'll practice accessing the different elements in each list. Remember that this is called indexing; we access an item in the list by calling it's index. And don't forget that Python is zero-indexed (for example, the second element would have an index of [1]).

### 1.1 Using the example lists from above, print out the third element from each list.

The three lists are `names`, `heights`, and `weights`.

In [2]:
# Print out the third element of each list

print("The third element of each list is:" , heights[2], weights[2], names[2])

The third element of each list is: 190 86.1 Bobby

### Solution 1.1: Run the cell below to see the answer.

In [3]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.1
print('The third element of each list is:', heights[2], weights[2], names[2])

The third element of each list is: 190 86.1 Bobby

### 1.2 Create a new empty list named 'bmi'.

Lists can be created so there is a place to store variables generated later. After you create the list, print it out to see that it's empty.

In [4]:
# Create your empty list named 'bmi'

bmi = []

# Print out the list

print(bmi)

[]

### 1.3 Combine the three lists into a new list where each element is a person's name, weight, and height. Call it "person_data". 

This is a more challenging task! Instead of the one-dimensional lists we have above, we're going to create the *nested list* that was demonstrated in the video lecture. There is more than one way to create this type of list; try using something like `[[nested list1], [nested list2]]` where the outside brackets indicate the list that holds the nested lists (inside brackets).

In [40]:
# Create your new list called 'person_data' below

person_data = []

person_data.append([names[0],weights[0],heights[0]])
person_data.append([names[1],weights[1],heights[1]])
person_data.append([names[2],weights[2],heights[2]])
person_data.append([names[3],weights[3],heights[3]])
person_data.append([names[4],weights[4],heights[4]])
person_data.append([names[5],weights[5],heights[5]])

# Print out your list to make sure it's correct

print(person_data)

[['John', 84.5, 184], ['Ryan', 81.8, 177], ['Bobby', 86.1, 190], ['Pete', 92.2, 188], ['Esther', 69.6, 159], ['Jane', 72.0, 166]]

### Solution 1.3 Run the cell below to check your answer.

In [9]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# Check the dimensions of your list
assert len(person_data) == 6, "Your list doesn't contain enough items."
assert len(person_data[0]) == 3, "Your nested lists are not correct."

print("Your list is correct.")

Your list is correct.

### 1.4 Retrieve the last element of person_data and set it equal to the variable `last`. You can print out your answer to check it.

In [17]:
# Create your variable below

last = person_data[-1]

# Print out your answer to check

print(last)

['Jane', 72.0, 166]

### Solution 1.4: Run the cell below to check your answer.

In [18]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.4

# Check that the last element was assigned to last
assert last, "Your variable hasn't been created."
assert last == person_data[-1], "You didn't select the correct index."

### 1.5 Retrieve the 2nd and 3rd elements from person_data. 

Assign these values to a variable called `second_third`.

In [19]:
# Create your variable below

second_third = person_data[1:3]

### Solution 1.5: Run the cell below to check your answer.

In [20]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.5

# Verify the correct elements were selected
assert second_third, "Your variable hasn't been created"
assert second_third == person_data[1:3], "You didn't select the correct indices"

### 1.6 Change the first element of person_data by increasing the weight to 84.9. Keep the other values unchanged.

Remember to correctly select the indices; there will be two you need to specify.

In [41]:
# Change the first element in your list

person_data[0][1] = 84.9

### Solution 1.6: Run the cell below to check your answer.

In [37]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.6

# Verify the first element was changed
assert person_data[0][1] == 84.9

print("Your answer is correct.")

Your answer is correct.

### 1.7 Add another person, Samantha, to person_data. Her height is 162 cm and her weight is 51.3 kg.

In [42]:
# Add Samantha to your list

person_data.append(["Samantha",51.3,162])
# Print out your updated list

print(person_data)

for person in person_data:
  for weight_value in person:
      print(weight_value)

[['John', 84.9, 184], ['Ryan', 81.8, 177], ['Bobby', 86.1, 190], ['Pete', 92.2, 188], ['Esther', 69.6, 159], ['Jane', 72.0, 166], ['Samantha', 51.3, 162]]
John
84.9
184
Ryan
81.8
177
Bobby
86.1
190
Pete
92.2
188
Esther
69.6
159
Jane
72.0
166
Samantha
51.3
162

### Solution 1.7: Run the cell below to check your answer.

In [43]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.7

# Verify that Samantha's data was added correctly
assert person_data[6] == ['Samantha', 51.3, 162]

### 1.8 Next, we'll insert an item into the list. We'll add in a new set of  name, height, and weight variables. For an individual named "Lambda Llama" add in a height of 180 cm and a weight of 140 kg. Add this item after the third item (which has an index of two).

In [44]:
# Insert your new item after the 3rd item

person_data.insert(3, ["Lambda Llama", 140, 180])

### Solution 1.8: Run the cell below to check your answer.

In [47]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.8

# Verify that Lambda Llama's data was added correctly
assert person_data[3] == ['Lambda Llama', 140, 180]

---

## Part 2: Loops

Write our what you think is for loop is, in your own words.

To automatically repeat an operation on a data rather than manually doing for each element of the data
  

---

### Solution 2.1: Here is a good explanation of a Python [for loop](https://www.digitalocean.com/community/tutorials/how-to-construct-for-loops-in-python-3).

### 2.2 Write a simple `for` loop to iterate over and print a number 10 times. 

You can use the `range` function with one or two arguments. Or you can explicitly write out a list of 10 values and then loop over it.

In [48]:
# Write your for loop below (loop over 10 numbers):

for item in range(9):
  print(item**2)

0
1
4
9
16
25
36
49
64

### 2.3 Write a `for` loop to cube integers from 11 to 15, inclusive (i.e. including 11 and 15).

You can include a `print` statement in your `for` loop to check your work. 

*Hint: The output should be:* `1331, 1728, 2197, 2774, 3375`

In [49]:
# Write your for loop below (integer cubing):

for item in range(11,16):
  print(item**3)

1331
1728
2197
2744
3375

### 2.4 Now, let's combine the above for loop with creating a list of numbers. Use a list inside the `for` loop to hold the results; name your list `cubed`.

In [52]:
# Create your for loop again and include a list
# (make sure to create an empty list first!)

cubed = []
for number in range(11,16):
  cubed.append(number**3)

print(cubed)

[1331, 1728, 2197, 2744, 3375]

### Solution 2.4: Run the cell below to check your answer.

In [53]:
# DO NOT EDIT THIS CELL
# SOLUTION 2.4

# Check that the list is equal to the cubes of: 11, 12, 13, 14, 15
assert len(cubed) == len(range(11,16)), "Your list is not the correct length."
assert cubed == [1331, 1728, 2197, 2744, 3375], "Your numbers are incorrect."

### 2.5 Use a `for` loop to calculate the BMI of each person.

Using the list you created above (`person_data`) to calculate the BMI for each individual.

The formula is as follows:

>$\frac{Weight(kg)}{Height(m)^2} = BMI$

Hint: You will iterate over one index; two of the other indices will remain the same i.e. you'll always want the first (height) and second (weight) element of each nested list.

*Additional hint:* Make sure you check the units of your input height measurements. The BMI formula uses meters (m) and your heights are in centimeters (cm). There are 100 cm in one m; to convert from cm to m, divide by 100.

In [84]:
# Write your BMI calculation loop here
# Inside the loop print out each value for the bmi 

BMI = []
for person in person_data:
  BMI.append(person[1]/(person[2]/100)**2)
  print(person[0], "'s BMI is ", round(BMI[person_data.index(person)],1), sep='')

John's BMI is 25.1
Ryan's BMI is 26.1
Bobby's BMI is 23.9
Lambda Llama's BMI is 43.2
Pete's BMI is 26.1
Esther's BMI is 27.5
Jane's BMI is 26.1
Samantha's BMI is 19.5

### 2.6 STRETCH GOAL: Do it using list comprehension.

For loops are one way to interate through a list or nested lists. But list comprehensions are more Pythonic way to accomplish the same thing.

In [92]:
#  Calculate the BMI using a list comprehension

# One way (suggestion)
BMI = [person[1]/(person[2]/100)**2 for person in person_data]
print(BMI)

# More Pythonic way (suggestion)
person_data
BMI = []
for x in person_data:
  BMI.append(x[1]/(x[2]/100)**2)
print(BMI)

[25.07679584120983, 26.109993935331477, 23.850415512465375, 43.20987654320987, 26.086464463558173, 27.530556544440483, 26.1286108288576, 19.547325102880652]
[25.07679584120983, 26.109993935331477, 23.850415512465375, 43.20987654320987, 26.086464463558173, 27.530556544440483, 26.1286108288576, 19.547325102880652]

---

### Submit your assignment notebook! (Make sure you've changed the name to FIRSTNAME_LASTNAME_assign2): 

1.  Click the Share button in the upper-right hand corner of the notebook.
2.  Get shareable link
3.  Set condition to: "Anyone with the link can comment"

---